<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LTIN216042" failures="1" tests="3" name="Test" time="1.039" errors="0" timestamp="2024-03-06T17:52:10 IST">
  <testcase classname="extentReport.MyTest" name="test1" time="0.031"/>
  <testcase classname="extentReport.MyTest" name="test2" time="0.031">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at extentReport.MyTest.test2(MyTest.java:14)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="extentReport.MyTest" name="test3" time="0.001">
    <skipped/>
  </testcase> <!-- test3 -->
</testsuite> <!-- Test -->
